### ISSUE TITLE
Check the RAP against the In Progress PPP

### ISSUE THREAD

**Issue by edickens** [FreeUKGen/FreeREGNonProductIssues#13]
The RAP will show all work that is in progress.  It will be useful to see who is very slow at transcribing or has had work for ages and not uploaded.

**Comment by Captainkirkdawson** [comment]
Still relevant?

**Comment by edickens** [comment]
No. E
    
    On 08/11/2015 20:26, Kirk Dawson wrote:
    
    
      Still relevant?
      —
        Reply to this email directly or view
          it on GitHub.
