### ISSUE TITLE
Add information on sources (e.g. Ancestry) to help

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#21]
The help pages need a warning to folk that they are only to use our images for transcription - not images downloaded from Ancestry, etc, under a contract that does not permit such use.

**Comment by PatReynolds** [comment]
Include link to https://www.gov.uk/government/publications/copyright-notice-digital-images-photographs-and-the-internet  and highlight in text "Simply creating a copy of an image won’t result in a new copyright in the new item."

**Comment by Captainkirkdawson** [comment]
Pat; Where and in what context? 

Copyright  never never really was an issue. Although many early copies purported to have such a copyright. The modern issue is the licence you accept to obtain access to the product. These normally prohibit what you can or cannot do.

**Comment by PatReynolds** [comment]
Hi Kirk: on the help pages - Eric and I have had a couple of people indicating that they are wanting to transcribe (in violation of their agreements with commercial companies) - this is a standing reminder to folk that they shouldn't.

**Comment by Captainkirkdawson** [comment]
But many people would read that and assume that they could use those images as there was no copyright. It does not address the issue of the licence one accepts in using a commercial product

**Comment by AlOneill** [comment]
So, if I understand correctly:
We cannot accept donations of **images** purchased from commercial sites such as Ancestry, FindMyPast, Scotlands People, &c, because the licence accepted by the purchaser permits only personal use of those images and their contents.
Neither can we accept the donation of a **transcript** (with the intention to convert to our format) made from such images because that too violates the licence conditions that permit only personal use.

This needs to be seen by transcribers, coordinators and potential donors.

**Comment by edickens** [comment]
Yes, that is correct.
    
    However, if someone uploads a transcription then we have to assume
    that it has been created legally.  We cannot double check the image
    source, nor do we have a means to do that.  We even need to go
    further and state in our Transcriber Agreement, that it is the
    responsibility of the Transcriber to ensure that they have the legal
    right to transcribe from the images that they are using and we
    cannot be held responsible for their breach of the Terms and
    Conditions associated with the images.
    
    If a transcriber wants to ignore this, then that is their problem,
    but the owner of the images has no way of knowing where the
    transcriber got the images.  An image of the original register is
    just that.  But if the transcriber uploads the images to our images
    server, then we cannot make these images available for the public. 
    It can be very obvious where the images came from because of the
    framing of the image and any additional coding.  For example on the
    images that we have digitised from microfiche/film we put a very
    small marker in the top left corner of each images, such as this...
    
    
    
    ...so that we can tell if anyone has "borrowed" our images.
    
    As most of our images have come from sources where we have
    permission just to transcribe, the default will have to be to assume
    that we cannot show these to the public.  FreeBMD and FreeCEN are
    completely different.
    
    E
    
    On 22/12/2015 15:53, AlOneill wrote:
    
    
      So, if I understand correctly:
        We cannot accept donations of images purchased
        from commercial sites such as Ancestry, FindMyPast, Scotlands
        People, &c, because the licence accepted by the purchaser
        permits only personal use of those images and their contents.
        Neither can we accept the donation of a transcript
        (with the intention to convert to our format) made from such
        images because that too violates the licence conditions that
        permit only personal use.
      This needs to be seen by transcribers, coordinators and
        potential donors. 
      —
        Reply to this email directly or view
          it on GitHub.

**Comment by EmJayFry** [comment]
On 22 Dec 2015 5:53 PM, AlOneill wrote:

> We cannot accept donations of *images* purchased from commercial sites such as
> Ancestry, FindMyPast, Scotlands People, &c, because the licence accepted by the
> purchaser permits only personal use of those images and their contents.

My understanding is that whilst ownership of the images is vested in the likes 
of Ancestry, the information contained within them is public and anyone can do 
anything with it.

-- 
Regards,
Mike Fry (Jhb)

**Comment by Captainkirkdawson** [comment]
It is disappointing that we continue to have these discussions. They have been the source of frustration for all of us for the 20 years that FreeReg has been around. We have been promised a clear policy position from the Trustees but that as far as I am aware has not been forthcoming in all aspects.

We know that a) the owner of the Parish Register is the Vicar of the Church. b) That the Church Vicar has a copyright on the register for 70 years; so any register closed before 1930 is out of copyright. (This is why you see all of the LDS copies stopping around 1900.) c) That the register is deposited with the Diocesan Records Office for safe keeping. The DSO is usually the County Records Office  d).The CRO or LDS or any other person have a 75 copyright on their original photographs of the original register. e) The person/organization making the photo can license its use to another entity such as us or Ancestry. That license can impose conditions on the use of the photo. f) Any copy of those original photos does not have a copyright in its own regard but the original conditions applied by the .original copyright holder still apply. g) If anyone uses a website they must accept the conditions applied by its owner. This is usually very clear in the case of a commercial entity. An individual must abide by those conditions or may be subject to legal action.h) The facts that are contained within the register are not themselves controlled in any way. i) Automated techniques to process and conduct no commercial research on the data on images does not require permission of the copyright owner providing the one has legal access to the image such as through a subscription j) One may not copy and make available any copyrighted material k) it is clear that the action of extracting the facts from a copyrighted image to which one has legal access when done for personal or non-commercial research is not a contravention of the copyright.

It is therefore not clear to me that someone reading and transcribing the facts from an image that they have paid a subscription to view and sharing that with a non commercial such as ourselves is a contravention of the copyright or any license that may have been granted to any third party such as ancestry.

A clear statement from the management on these matters would be wonferful
