### ISSUE TITLE
Update references to Free UK Genealogy to reflect change to CIO

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#24]
From date tbc  - where we give the registered charity number, this is now: 1167484.  Where name is formal (e.g. where registered number is used) Free UK Genealogy should be changed to Free UK Genealogy CIO.

**Comment by Captainkirkdawson** [comment]
See 1004 for FreeREG action

**Comment by PatReynolds** [comment]
Date now confirmed as 1 January 2017

**Comment by Captainkirkdawson** [comment]
Done on FR

**Comment by PatReynolds** [comment]
Thank you!
