### ISSUE TITLE
Are our messages sent out too quickly? Can we fake slow messages?

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#29]
Eric B. has noted that a spam filter on Genuki identifies spam by time spent composing messages. He  "spent 83 seconds composing their message (<20 is treated as spam)".  Is this what is causing some users problems?

**Comment by DeniseColbert** [comment]
This is the type of filter Bev uses for the Free UK Gen contact form. Do Genuki use it on their contact forms, or for something similar to our messaging system?

**Comment by Sherlock21** [comment]
It was me who came across this.

I had used Genuki's website firm to report a wrongly placed church.

and the email from which Pat took the quote above was a reply from one of the Genuki volunteers. it was part of a bigger (Genuki) identifier bundle.as follows.

Dear GENUKI,
This originates from the Churches: Churchmap page 
[http://www.genuki.org.uk/cgi-bin/churchmap?GR=SX801605,D=3]
The user is at 137.138.159.143.dyn.plus.net,
using browser Mozilla/5.0 (Macintosh; Intel Mac OS X 10_9_5) AppleWebKit/601.7.8 (KHTML, like Gecko) Version/9.1.3 Safari/537.86.7.
and spent 83 seconds composing their message (<20 is treated as spam).

End of copy EB.

**Comment by Captainkirkdawson** [comment]
Sorry but this illogical. 

It confuses filling in a form and submitting that with generating and sending an email.  It also confuses robotic actions with spam, They are both totally different processes. 

It is possible for a browser to report on the time taken to fill in a form and we and othes use that to detect bots (computer programs pretending to be people) not spam.

It is not possible for a browser to report how long it has taken someone to compose an email. It simply has no information . Most of the latter are done off line and go no where near a browser and there is nothing in an email package that could be used to say the message was spam based on  length of time to compose.

**Comment by Sherlock21** [comment]
I beg to differ that its illogical and confusing on the part of the commentator or the fact quoted.
It is an exact statement of occurrence.

It may be irrelevant of course, but thats a different matter. I don't know how your email system functions, ( the one that seems to be x=causing s much paint to some, with apparent Trash/ spam / spoof emails.

If its totally irrelevant I will remove it, so as to keep this issue clear of misguided information

**Comment by Captainkirkdawson** [comment]
The facts as stated in your post are correct and not disputed as they relate to the filling in and processing of forms

What is illogical is to take what happens with the form based system and apply it to the distinctly different process of emailing.
