### ISSUE TITLE
Data for transcription

### ISSUE THREAD

**Issue by Captainkirkdawson** [FreeUKGen/FreeREGNonProductIssues#30]
Increase the availability of data for transcription by adopting a systematic approach to the custodians of the records

**Comment by edickens** [comment]
We  have quite a lot, but only in a few counties and some of that is either not good quality or is old script.

**Comment by Captainkirkdawson** [comment]
interesting comment by Rod Neep made in 2000 on the question of copyright and availability.

http://archiver.rootsweb.ancestry.com/th/read/FREEREG/2000-01/0948307820

We have evolved little in the past 17 years.

**Comment by SteveBiggs** [comment]
A meeting was held between interested parties on June 8th and some actions agreed. Minutes will be sent out via email.

**Comment by PatReynolds** [comment]
Apologies - did not mean to close.  I have put up my tasks from the meeting as individual stories.  #1248 #1249
