### ISSUE TITLE
Decide 'role' for JS (Volunteering Q contacts)

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeREGNonProductIssues#39]
JS is currently a CC but needs access to Volunteering Questions in Contacts. JS also deals with Training new transcribers.

Vino proposes to make JS Volunteer Coordinator:

A person can have only one role but what we can do instead is when we change the role to volunteer_coordinator, we can make the actions of county coordinator also available to volunteer coordinator. This was once suggested by Kirk long before.
JS will be the only volunteer_coordinator in our database.

Is there the role of Training Coordinator? If not,  is Volunteer Coordinator the correct role for JS?

**Comment by PatReynolds** [comment]
I would have said that JS is Training rather than Volunteering.  When you say "we can make the actions of county coordinator also available to volunteer coordinator" do you mean 'actions of all CCs' or just of JC's county?

**Comment by SteveBiggs** [comment]
@PatReynolds as well as being trainer, JS has taken over the position of Volunteer Coord (VC).
@DeniseColbert  There is no role of Training Coord.
I don't believe the VC role should be able to manage _any_ county as a CC, but clearly JS needs to continue managing LAN.
The one action a VC has that a CC does not is Manage (all) UserIds. I think JS can operate without this action - if she needs userids to be moved, she asks me and I do it which seems to work.
So I suggest she remains as a CC role for LAN.

**Comment by DeniseColbert** [comment]
@Vino-S Can JS (as per our email conversation last week) remain as LAN County Coord, but still have Volunteering Question contacts appear in her Actions?

**Comment by SteveBiggs** [comment]
@DeniseColbert that's a good point. I think it will get messy if we make Volunteering Question contacts visible under Jo's CC login because if/when someone else takes over, the contacts would then have to be moved again and so on. Perhaps it would be neater if we created a separate userid for the VC that Jo can use now and would be passed on to whoever takes over in future?

**Comment by SteveBiggs** [comment]
... or we could incorporate the CC actions into the VC role, but the VC can only manage the counties/syndicates that their login allows. So in Jo's case when she logs in as VC, she can only manage LAN and the same syndicates that she presently does? (this is probably what Kirk had in mind)

**Comment by Vino-S** [comment]
At present Jo's userid is hardcoded for volunteering queries and Kirk had suggested me the same solution.
I personally think it would be better if Jo has separate userid as volunteer coordinator as per @SteveBiggs  suggestions( if it is fine with Jo to manage two accounts). At present we do not have have any volunteer coordinator in our database.

**Comment by Vino-S** [comment]
@DeniseColbert CC's have access to "Contacts" action which lists the data_problem reports. 
If Jo continues to manage single account as CC/VC
 what we can do is show her the 2 lists
1.  lists of data_problem reports
2. list of Volunteering Question.
As this implementation is only for Jo we might again require hard coding.
Let me know your suggestions.

**Comment by SteveBiggs** [comment]
I would prefer we keep the VC role separate and Jo has a separate userid as @Vino-S suggests. The VC may not always be a CC and even if it is, when the person changes, the hard coding would have to change each time. A separate userid is the neatest solution and Jo is used to having more than userid already.

**Comment by DeniseColbert** [comment]
I think the second option might be more convenient for Jo

**Comment by SteveBiggs** [comment]
Need to ask @Vino-S if it's possible to do that without hard coding that would need re-coding everytime the person doing the VC role changed.

**Comment by Vino-S** [comment]
I had created a new field in UseridDetail model "secondary_role" which is an array so that a person can have multiple secondary roles. This way we can avoid hard-coding.
 Following are the details
1. Eric's secondary_role: "genealogy_coordinator", "general_communication_coordinator", "publicity_coordinator"
2. Steve's secondary_role: "website_coordinator"
3. Jo' secondary_role: "volunteer_coordinator"

**Comment by DeniseColbert** [comment]
Sounds like an ideal solution!

**Comment by Vino-S** [comment]
Updated in live and test3.
