### ISSUE TITLE
CCs can reply to contacts from within Message System

### ISSUE THREAD

**Issue by DeniseColbert** [FreeUKGen/FreeREGNonProductIssues#40]

**Comment by DeniseColbert** [comment]
Can this be re-labelled to Features?

**Comment by PatReynolds** [comment]
I _think_ you would need to delete and re-create it in the repository for "Features" (on Github).  I know that one repository is just handling the issues raised system, but not sure what the others are for ....  When you or I raise issues, they go into "Management".  I don't think we use the "Features", "Management" etc for anything in terms of project management (but happy to be corrected on any/all of the above).

**Comment by SteveBiggs** [comment]
Also need the ability within message system to reply to Feedbacks.

**Comment by richpomfret** [comment]
Closing as new story has been created.
