### ISSUE TITLE
Add message to those blocking adverts

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#41]
Message to explain that we are a charity, adverts are a vital part of our income, and that if you prefer not to see adverts, please consider making a donation

Priority (4, 3, 7, 6) 20

**Comment by SteveBiggs** [comment]
@PatReynolds I agree with the sentiment, but is it the case that if they make a donation it stops them seeing the adverts?

**Comment by richpomfret** [comment]
We would need to clarify that donating does not remove adverts (although that's a potential next approach at some point, although rather more complex).

**Comment by PatReynolds** [comment]
Could make 'adverts' e.g. for recycle4good, easyfundraising, etc.

**Comment by DeniseColbert** [comment]
Some draft designs in Projects folder of drive

**Comment by PatReynolds** [comment]
Sent feedback 17/09/2018

**Comment by richpomfret** [comment]
@DeniseColbert any update on this?

**Comment by richpomfret** [comment]
@smrr723 this would be a nice one to get done during this sprint (particularly as it has been working well on FC2 for a while).

**Comment by smrr723** [comment]
Banner with hyperlink added - will be in production after the update (available on test3 for testing).
