### ISSUE TITLE
Count number of transcribers / Open Data status

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#43]
A report for Trustees (and other interested parties) recording (weekly) how many individual transcribers there are on FreeREG, and how many in each Transcriber Agreement status.

Priority
Economic 4
Urgency 1
Strategic 7
Cost 7

**Comment by edickens** [comment]
Are there any other interesting management statistics?  Such as how many transcribers actually uploaded data?  How many new transcribers?  How many left?  How many never completed registration?

**Comment by Vino-S** [comment]
We can create an Action which will show all the statistics. The page will also include a graphical representation. 
Useful stats:
1. Total transcribers
2. Total transcribers who Accepted Transcription Agreement
3. Percentage of transcribers Accepted Transcription Agreement
4. Active transcribers
5.  how many transcribers actually uploaded data---as Eric suggested
6. How many never completed registration?---as Eric suggested

**Comment by edickens** [comment]
I suggest that we don't need 3., but show each of the others as a total and a percentage of 1.
Remember that later on Researchers will also be able to register, but they should be in separate statistics.

**Comment by Sherlock21** [comment]
I agree with Eric d that 3. is not relevant on its own.
BUT 4) 5) and 6) need to identify whether they  in group 1) or in group 2)

- Else in the extreme, all the uploaded data could belong to Transcribers who are not in 2) and you would be thinking that you have a lot of Open Data when in fact thats not true.

**Comment by edickens** [comment]
Good point EricB.  I had forgotten that it would be very useful to see how many had agreed to let their transcriptions be Open Data so that we can promote it.

**Comment by PatReynolds** [comment]
I've asked for 3.  I will find it useful, as we have not yet contacted inactive transcribers (and won't do for some time. 
Another one: total number of records made open by Transcribers (and percentage).

**Comment by smrr723** [comment]
Deployed to production.

**Comment by PatReynolds** [comment]
Working ok, but not displaying the statistics requested (if https://www.freereg.org.uk/site_statistics? is the correct page to view).

Also needed: number of records now Opened by Transcriber.

**Comment by richpomfret** [comment]
Returning to the backlog.

**Comment by smrr723** [comment]
The correct page for the statistics is - https://www.freereg.org.uk/userid_details/transcriber_statistics which does appear to have all the statistics required?

**Comment by PatReynolds** [comment]
Still needs:
number of records now Opened by Transcriber
number of transribers who have not uploaded records but have signed the agreement

I can work out everything else with these.

**Comment by PatReynolds** [comment]
Not sure I can work out percentages - this is what I report on:
1. Total Users: 2664 (2575)
2. Total Users who Accepted Transcription Agreement: 298 (171)
3. Percentage of total users Accepted Transcription Agreement: 11.2% (6.6%)
4. Percentage of existing users Accepted Transcription Agreement: (4.4%)
5. Percentage of existing active users Accepted Transcription Agreement: tbc
---------------------------------------------------------------------

Number of new users signed up in FreeREG in past 30 days: (22)
Number of new users signed up in FreeREG in past 90 days: (60)

**Comment by smrr723** [comment]
Just to clarify, I will be adding the following:-

- Number of records opened by transcribers
- % of above which are opened by transcribers
- Transcribers who signed the agreement but didn't upload a record
- % of total users who accepted the transcription agreement
- % of total ACTIVE users who accepted the transcription agreement

The only ones I'm unsure about is point's 3 & 4 which you mention above -  what's the difference between "total users" and "existing users"?

**Comment by PatReynolds** [comment]
Existing users are those who were existing before we went live with insisting that new users sign the agreement.  
Existing active users are those existing users who are marked active.

**Comment by smrr723** [comment]
Ok, thanks - Total & Existing are clear now.

And "existing active" I'm taking to mean users who were around before 11/10/17, who are also active.

**Comment by Sherlock21** [comment]
Following the link above, to view these stats, I just get barred with a message: you are not Authorised to see this doc.

can you reconsider that decision please?

**Comment by SteveBiggs** [comment]
@Sherlock21 Site Stats are only available to the roles - Technical, Sys Admin, Project Mng and Exec Dir.

**Comment by PatReynolds** [comment]
Thanks, @smrr723 yes, existing active are those who were around before 11/10/17, and are marked as active.

**Comment by smrr723** [comment]
One more thing @PatReynolds - about the "Number of records opened by transcribers".  Is this stat different to what is shown on the site_stats page here - https://www.freereg.org.uk/site_statistics ?

Each user has a parameter called `number_of_records`, so I was just going to sum the total of these, for all transcriber roles. I see nothing about whether a record is 'opened' or not.  Is this correct, or is there more to this?

**Comment by Sherlock21** [comment]
Re: Steve's reply to my above post:-

Then don't send me an email inviting me to look at the message that I am not then permitted to read!

**Comment by helhyde** [comment]
Search transcriber is linked to a number of records. It is the total of
records where the transcriber has signed the agreement that is needed

Pat

Executive Director, Free UK Genealogy

**Comment by smrr723** [comment]
Got it, thanks Pat.

**Comment by smrr723** [comment]
Live on test3 - but apparently, no "record" data on there to verify if the top two new rows are fetching data correctly (number & percentage of records).  All the others work as expected.

Pushing to production shortly.

**Comment by smrr723** [comment]
Stats now live @PatReynolds
