### ISSUE TITLE
Meet TNA 28/10/18

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#46]
Priority 25 (6	4	9	6)

**Comment by Captainkirkdawson** [comment]
I do not understand this story

**Comment by PatReynolds** [comment]
Email sent 29/8/2018

**Comment by PatReynolds** [comment]
Chased 13/9/2018

**Comment by PatReynolds** [comment]
Email re discussion sent to project team 2/11/2018

**Comment by Captainkirkdawson** [comment]
Guess I am not member of project team. Pity I would have been interested

**Comment by Sherlock21** [comment]
Kirk:
you are not the only one who can't make head nor tale of this.

More like a snip from someones personal diary rather than a usual FR story.
