### ISSUE TITLE
Review current status of Communications (tag)

### ISSUE THREAD

**Issue by PatReynolds** [FreeUKGen/FreeREGNonProductIssues#58]
Compare original proposals/requirements against current functionals

**Comment by richpomfret** [comment]
To include looking at priority of remaining tasks, move 'should have' or 'could haves' into future milestone or iteration.

**Comment by PatReynolds** [comment]
I have reviewed everything with a Blue or White 'Communications' label.  Those things which are about communication, but not about the communication system (messages/feedback/comment) I have = changed to a white Communications non-system' label, so they are not selected by filtering on Communications'

There are a few stories which _might_ be system or might not.  I.e. 1505, 1457 and 1195  These can be changed to Communication-non system, if not.

I would like to suggest including in the next release all 'Communications' of Priority 18 and above.

**Comment by Captainkirkdawson** [comment]
IMHO 1505, 1457 and 1195 are not com system so have removed that designation

**Comment by Captainkirkdawson** [comment]
Do not see dependency story #68

**Comment by PatReynolds** [comment]
Depencency a typo - now corrected.
